1 add loadmore button
domainslab/client pull request #5
Opened 2023-10-07 14:21 UTC by artkon2712

2023-10-08 09:42 UTC, greenwookez commented
please write at least couple of words about this PR in the description so we can document the meaning of this code
ideally, description should contain screenshots of the implemented feature to make it easier to understand and QA/CR

2023-10-08 11:09 UTC, greenwookez requested changes

2023-10-08 11:09 UTC, greenwookez commented on src/services/api/MakeBaseRequest.ts
let's rename this file to base.ts so we can use it for other generic functions for API services in future

2023-10-08 11:09 UTC, greenwookez commented on src/services/api/MakeBaseRequest.ts
> +export const makeGetBaseRequest = (featureURL, options: {params, headers}) : Promise<AxiosResponse> => {
let's rename it to just `get` to keep it simple

2023-10-08 11:09 UTC, greenwookez commented on src/services/api/MakeBaseRequest.ts
I would also make this function more generic so it can take a type for the API's response

2023-10-08 11:09 UTC, greenwookez commented on src/contexts/DomainContext/DomainContextProvider.tsx
> +export const DomainContext = createContext(undefined)
please make a type for this context, create an initialising object and move it out from `DomainContextProvider` component
ideally, the provider itself shouldn't contain any business logic
this logic should be places inside the parent component that hosts this provider

2023-10-08 11:09 UTC, greenwookez commented on src/pages/Home/components/DomainList.tsx
> +  const [localLoading, setLocalLoading] = useState(false)
please move localLoading state to the `DomainContext` and name it in the way we name boolean states, e.g. `isMoreLoading`

2023-10-08 11:09 UTC, greenwookez commented on src/pages/Home/components/useSearch.ts
if we don't need this hook anymore, just delete it

2023-10-08 11:10 UTC, greenwookez commented
in general, please make sure that:
eslint and prettier work fine in accordance with the provided configs
there is no any meaningful commented code

2023-10-08 17:05 UTC, azrv requested changes

2023-10-09 14:01 UTC, artkon2712 commented on src/services/api/RequestAvailability.ts
Done

2023-10-09 14:01 UTC, artkon2712 commented on src/services/api/RequestAvailability.ts
> +    headers:
Done

2023-10-09 14:01 UTC, artkon2712 commented on src/services/api/RequestAvailability.ts
> +const URL = 'domain_status'
Done

2023-10-09 14:01 UTC, artkon2712 commented on src/services/api/RequestDomains.ts
> +export function getNewDomainListRequest(prompt,tlds){
Done

2023-10-09 14:01 UTC, artkon2712 commented on src/services/api/MakeBaseRequest.ts
> +export const makeGetBaseRequest = (featureURL, options: {params, headers}) : Promise<AxiosResponse> => {
Done

2023-10-09 14:02 UTC, artkon2712 commented on src/contexts/DomainContext/DomainContextProvider.tsx
> +export const DomainContext = createContext(undefined)
Done

2023-10-09 14:02 UTC, artkon2712 commented on src/pages/Home/components/DomainList.tsx
> +  const [localLoading, setLocalLoading] = useState(false)
Done

2023-10-09 14:02 UTC, artkon2712 commented on src/pages/Home/components/useSearch.ts
Deleted

2023-10-09 14:02 UTC, artkon2712 commented on src/contexts/DomainContext/DomainContextProvider.tsx
> +  const [domains, setDomains] = useState<Domain[] | null>([])
Done

2023-10-09 14:02 UTC, artkon2712 commented on src/contexts/DomainContext/DomainContextProvider.tsx
> +      .then(res=>setDomains(addDomainsToExisting(res.data.domains)))
Done

2023-10-09 14:04 UTC, artkon2712 commented on src/pages/Home/components/DomainList.tsx
> +                <Button {...{ onClick : onButtonClick  }}>Load More...</Button>) : <Loader />
Using custom Button component, not html tag
exp: Home/components/search.tsx (135:9)

2023-10-09 15:44 UTC, artkon2712 commented on src/services/api/MakeBaseRequest.ts
Name changed

2023-10-10 09:09 UTC, greenwookez requested changes

2023-10-10 09:09 UTC, greenwookez commented on src/contexts/DomainContext/DomainContext.tsx
> +  addMoreDomains(): Promise<AxiosResponse> {return ;},
let's rename `addMoreDomains` to `loadMoreDomains`
type: () => void
intialization: loadMoreDomains: () => null
implementation (in HomeWithContext.tsx): 
```
const loadMoreDomains = async () =>{
    const response = await getDomains(lastPrompt, lastTlds)
    setDomains(prevDomains => [...prevDomains, ...response.data.domains])
  }
```

2023-10-10 09:09 UTC, greenwookez commented on src/contexts/DomainContext/DomainContext.tsx
> +  addMoreDomains(): Promise<AxiosResponse> {return ;},
the point here is to get rid of `AxiosResponse` type, it should be incapsulated on the api service level

2023-10-10 12:05 UTC, artkon2712 commented on src/pages/Home/Home.tsx
> +              isLoading && domains == [] ? (<div className='flex flex-col items-center mt-[30px]'><Loader /></div>) : (
Done

2023-10-10 12:05 UTC, artkon2712 commented on src/pages/Home/Home.tsx
> +  const {isLoading, domains} = useContext(DomainContext)
Done

2023-10-10 12:05 UTC, artkon2712 commented on src/contexts/DomainContext/DomainContext.tsx
done

2023-10-10 12:05 UTC, artkon2712 commented on src/services/api/base.ts
> +export const get = <T>(featureURL, options: {params}) : Promise<AxiosResponse> => {
Done

2023-10-10 12:06 UTC, artkon2712 commented on src/services/api/GetDomainStatus.ts
> +export function getDomainStatus(title){
Done

2023-10-10 12:06 UTC, artkon2712 commented on src/pages/Home/components/Search.tsx
> +  const inputRef = useRef<HTMLInputElement | null>(null);
Done

2023-10-10 12:06 UTC, artkon2712 commented on src/pages/Home/components/Search.tsx
> +  const { setDomains, setLoading, setLastPrompt, setLastTlds } = useContext(DomainContext)
Done

2023-10-10 12:06 UTC, artkon2712 commented on src/pages/Home/components/DomainList.tsx
Done

2023-10-10 12:06 UTC, artkon2712 commented on src/contexts/DomainContext/DomainContext.tsx
> +  addMoreDomains(): Promise<AxiosResponse> {return ;},
Done

2023-10-10 12:07 UTC, artkon2712 commented on src/services/api/GetDomains.ts
> +export function getDomains(prompt,tlds){
Done

2023-10-14 10:47 UTC, greenwookez approved these changes
well done, thanks

2023-10-14 10:47 UTC, azrv approved these changes

2023-10-22 09:20 UTC, merged